In [2]:
import os

print(os.path.abspath(os.curdir))

C:\Users\arez_\PycharmProjects\AMLS_19-20_Muhammad_Juzaimi_SN16072927


In [3]:
os.chdir('./AMLS_19-20_SN16072927')
os.chdir('./A2')
print(os.path.abspath(os.curdir))

C:\Users\arez_\PycharmProjects\AMLS_19-20_Muhammad_Juzaimi_SN16072927\AMLS_19-20_SN16072927\A2


In [6]:
import A2_landmarks as l2
import numpy as np 
from sklearn.model_selection import train_test_split

def get_data():

    X_A2, y = l2.extract_features_labels()
    Y_A2 = np.array([y, -(y - 1)]).T
    

    return X_A2, Y_A2


In [7]:
X_A2, Y_A2 = get_data()

In [8]:
print(len(X_A2))
print(len(Y_A2))


4803
4803


In [9]:
print(X_A2)
print(Y_A2)


[[[ 59 113]
  [ 57 123]
  [ 57 133]
  ...
  [ 88 163]
  [ 83 163]
  [ 78 161]]

 [[ 55 110]
  [ 54 120]
  [ 54 131]
  ...
  [ 89 163]
  [ 83 163]
  [ 78 161]]

 [[ 44 102]
  [ 45 115]
  [ 47 127]
  ...
  [ 94 160]
  [ 89 161]
  [ 84 161]]

 ...

 [[ 48 115]
  [ 50 126]
  [ 52 137]
  ...
  [ 91 158]
  [ 87 158]
  [ 83 157]]

 [[ 60 116]
  [ 59 125]
  [ 60 134]
  ...
  [ 89 153]
  [ 85 153]
  [ 80 152]]

 [[ 52 111]
  [ 52 121]
  [ 53 132]
  ...
  [ 91 158]
  [ 86 158]
  [ 81 157]]]
[[ 1. -0.]
 [ 1. -0.]
 [ 1. -0.]
 ...
 [ 0.  1.]
 [ 0.  1.]
 [ 1. -0.]]


In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
temp = X_A2.reshape(len(X_A2), 68*2)
temp_X_A2 = scaler.fit_transform(temp)
temp_Y_A2 = list(zip(*Y_A2))[0]

In [22]:
print(temp_X_A2)
print(temp_Y_A2)

[[ 1.39723694 -0.03505051  1.23277142 ...  1.51293901 -1.58053177
   1.20255988]
 [ 0.98432657 -0.68840479  0.90328998 ...  1.51293901 -1.58053177
   1.20255988]
 [-0.15117695 -2.43068286 -0.08515434 ...  0.97787929  0.16332384
   1.20255988]
 ...
 [ 0.26173342  0.400519    0.46398139 ...  0.17528971 -0.12731877
   0.07955495]
 [ 1.50046453  0.61830376  1.45242571 ... -1.16235959 -0.99924657
  -1.32420121]
 [ 0.67464379 -0.47062003  0.68363569 ...  0.17528971 -0.70860397
   0.07955495]]
(1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.

In [25]:
import pickle

with open('X_A2_saved.dat', 'wb') as f:
    pickle.dump(temp_X_A2, f) 
    
with open('Y_A2_saved.dat', 'wb') as f:
    pickle.dump(temp_Y_A2, f) 

In [26]:
with open('X_A2_saved.dat', 'rb') as f:
    X_A2_load = pickle.load(f)
    
with open('Y_A2_saved.dat', 'rb') as f:
    Y_A2_load = pickle.load(f)

In [27]:
print(len(X_A2_load))
print(X_A2_load)
print(len(Y_A2_load))
print(Y_A2_load)

4803
[[ 1.39723694 -0.03505051  1.23277142 ...  1.51293901 -1.58053177
   1.20255988]
 [ 0.98432657 -0.68840479  0.90328998 ...  1.51293901 -1.58053177
   1.20255988]
 [-0.15117695 -2.43068286 -0.08515434 ...  0.97787929  0.16332384
   1.20255988]
 ...
 [ 0.26173342  0.400519    0.46398139 ...  0.17528971 -0.12731877
   0.07955495]
 [ 1.50046453  0.61830376  1.45242571 ... -1.16235959 -0.99924657
  -1.32420121]
 [ 0.67464379 -0.47062003  0.68363569 ...  0.17528971 -0.70860397
   0.07955495]]
4803
(1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.