In [1]:
import os

print(os.path.abspath(os.curdir))

C:\Users\arez_\PycharmProjects\AMLS_19-20_Muhammad_Juzaimi_SN16072927


In [2]:
os.chdir('./AMLS_19-20_SN16072927')
os.chdir('./B1')
print(os.path.abspath(os.curdir))

C:\Users\arez_\PycharmProjects\AMLS_19-20_Muhammad_Juzaimi_SN16072927\AMLS_19-20_SN16072927\B1


In [3]:
import B1_landmarks as b1l
import numpy as np 

def get_data():

    X_B1, y, _ = b1l.extract_features_labels()
    Y_B1 = np.array([y, -(y - 1)]).T
    

    return X_B1, Y_B1

Using TensorFlow backend.


In [4]:
X_B1, Y_B1 = get_data()

In [5]:
print(len(X_B1))
print(len(Y_B1))

7815
7815


In [6]:
print(X_B1)
print(Y_B1)

[[[150 280]
  [152 304]
  [155 327]
  ...
  [263 347]
  [253 348]
  [242 348]]

 [[165 256]
  [168 279]
  [172 303]
  ...
  [257 351]
  [250 353]
  [242 351]]

 [[159 249]
  [161 274]
  [165 298]
  ...
  [258 351]
  [249 354]
  [239 352]]

 ...

 [[181 259]
  [183 279]
  [188 299]
  ...
  [258 347]
  [251 349]
  [242 348]]

 [[165 259]
  [169 281]
  [173 301]
  ...
  [256 351]
  [249 352]
  [241 350]]

 [[166 255]
  [170 278]
  [176 298]
  ...
  [256 345]
  [249 346]
  [241 344]]]
[[ 4 -3]
 [ 4 -3]
 [ 0  1]
 ...
 [ 2 -1]
 [ 2 -1]
 [ 2 -1]]


In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
temp = X_B1.reshape(len(X_B1), 68*2)
temp_X_B1 = scaler.fit_transform(temp)
temp_Y_B1 = list(zip(*Y_B1))[0]

In [8]:
print(temp_X_B1)
print(temp_Y_B1)

[[-2.33210837  2.72112982 -2.67870581 ...  0.02410281  0.60574548
   0.33373719]
 [ 0.36401388  0.12458065  0.46649837 ...  0.90184505  0.60574548
   0.86152597]
 [-0.71443502 -0.6327462  -0.90952845 ...  1.0773935  -0.64396437
   1.03745556]
 ...
 [ 3.23987761  0.44914929  3.41512729 ...  0.19965126  0.60574548
   0.33373719]
 [ 0.36401388  0.44914929  0.66307364 ...  0.7262966   0.18917553
   0.68559638]
 [ 0.54375536  0.0163911   0.8596489  ... -0.32699408  0.18917553
  -0.36998117]]
(4, 4, 0, 2, 3, 3, 4, 4, 4, 1, 0, 3, 3, 0, 2, 4, 3, 4, 0, 3, 0, 2, 3, 4, 2, 4, 0, 2, 4, 2, 0, 4, 2, 3, 3, 4, 4, 2, 0, 3, 4, 0, 0, 2, 3, 3, 4, 1, 1, 3, 3, 2, 1, 0, 4, 3, 0, 0, 3, 2, 3, 4, 4, 4, 4, 2, 3, 4, 3, 0, 4, 4, 3, 3, 3, 0, 2, 4, 3, 3, 2, 1, 4, 3, 4, 3, 0, 1, 4, 4, 4, 2, 0, 2, 0, 0, 3, 4, 4, 1, 0, 1, 4, 3, 0, 4, 2, 0, 1, 0, 2, 1, 3, 2, 2, 3, 0, 2, 1, 1, 4, 0, 1, 2, 1, 4, 4, 4, 1, 2, 3, 0, 4, 1, 3, 0, 2, 2, 2, 0, 1, 0, 4, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 1, 2, 4, 3, 0, 2, 4, 1, 0, 1, 4, 0, 1, 1, 1, 4, 

In [9]:
import pickle

with open('X_B1_saved.dat', 'wb') as f:
    pickle.dump(temp_X_B1, f) 
    
with open('Y_B1_saved.dat', 'wb') as f:
    pickle.dump(temp_Y_B1, f) 

In [12]:
with open('X_B1_saved.dat', 'rb') as f:
    X_B1_load = pickle.load(f)
    
with open('Y_B1_saved.dat', 'rb') as f:
    Y_B1_load = pickle.load(f)

In [13]:
print(len(X_B1_load))
print(X_B1_load)
print(len(Y_B1_load))
print(Y_B1_load)

7815
[[-2.33210837  2.72112982 -2.67870581 ...  0.02410281  0.60574548
   0.33373719]
 [ 0.36401388  0.12458065  0.46649837 ...  0.90184505  0.60574548
   0.86152597]
 [-0.71443502 -0.6327462  -0.90952845 ...  1.0773935  -0.64396437
   1.03745556]
 ...
 [ 3.23987761  0.44914929  3.41512729 ...  0.19965126  0.60574548
   0.33373719]
 [ 0.36401388  0.44914929  0.66307364 ...  0.7262966   0.18917553
   0.68559638]
 [ 0.54375536  0.0163911   0.8596489  ... -0.32699408  0.18917553
  -0.36998117]]
7815
(4, 4, 0, 2, 3, 3, 4, 4, 4, 1, 0, 3, 3, 0, 2, 4, 3, 4, 0, 3, 0, 2, 3, 4, 2, 4, 0, 2, 4, 2, 0, 4, 2, 3, 3, 4, 4, 2, 0, 3, 4, 0, 0, 2, 3, 3, 4, 1, 1, 3, 3, 2, 1, 0, 4, 3, 0, 0, 3, 2, 3, 4, 4, 4, 4, 2, 3, 4, 3, 0, 4, 4, 3, 3, 3, 0, 2, 4, 3, 3, 2, 1, 4, 3, 4, 3, 0, 1, 4, 4, 4, 2, 0, 2, 0, 0, 3, 4, 4, 1, 0, 1, 4, 3, 0, 4, 2, 0, 1, 0, 2, 1, 3, 2, 2, 3, 0, 2, 1, 1, 4, 0, 1, 2, 1, 4, 4, 4, 1, 2, 3, 0, 4, 1, 3, 0, 2, 2, 2, 0, 1, 0, 4, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 1, 2, 4, 3, 0, 2, 4, 1, 0, 1, 4, 0, 1,