In [4]:
import os

# os.chdir('./AMLS_19-20_Muhammad_Juzaimi_SN16072927')
# os.chdir('./AMLS_19-20_SN16072927')
os.chdir('./A1')
print(os.path.abspath(os.curdir))


C:\Users\arez_\PycharmProjects\AMLS_19-20_Muhammad_Juzaimi_SN16072927\AMLS_19-20_SN16072927\A1


In [6]:
# os.chdir('./A1')

import A1_landmarks as l1
import numpy as np 

def get_data():

    X, y = l1.extract_features_labels()
    Y = np.array([y, -(y - 1)]).T
    
    return X, Y
X, Y = get_data()
print(X)
print(Y)

Using TensorFlow backend.


[[[ 59 113]
  [ 57 123]
  [ 57 133]
  ...
  [ 88 163]
  [ 83 163]
  [ 78 161]]

 [[ 55 110]
  [ 54 120]
  [ 54 131]
  ...
  [ 89 163]
  [ 83 163]
  [ 78 161]]

 [[ 44 102]
  [ 45 115]
  [ 47 127]
  ...
  [ 94 160]
  [ 89 161]
  [ 84 161]]

 ...

 [[ 48 115]
  [ 50 126]
  [ 52 137]
  ...
  [ 91 158]
  [ 87 158]
  [ 83 157]]

 [[ 60 116]
  [ 59 125]
  [ 60 134]
  ...
  [ 89 153]
  [ 85 153]
  [ 80 152]]

 [[ 52 111]
  [ 52 121]
  [ 53 132]
  ...
  [ 91 158]
  [ 86 158]
  [ 81 157]]]
[[ 0.  1.]
 [ 0.  1.]
 [ 0.  1.]
 ...
 [ 0.  1.]
 [ 1. -0.]
 [ 0.  1.]]


In [6]:
print(len(X))
print(len(Y))

4803
4803


In [15]:
from sklearn.preprocessing import StandardScaler

temp = X.reshape(len(X), 68*2)

scaler = StandardScaler()
temp_X = scaler.fit_transform(temp)


In [16]:
print(len(temp_X))
print(temp_X)

4803
[[ 1.39723694 -0.03505051  1.23277142 ...  1.51293901 -1.58053177
   1.20255988]
 [ 0.98432657 -0.68840479  0.90328998 ...  1.51293901 -1.58053177
   1.20255988]
 [-0.15117695 -2.43068286 -0.08515434 ...  0.97787929  0.16332384
   1.20255988]
 ...
 [ 0.26173342  0.400519    0.46398139 ...  0.17528971 -0.12731877
   0.07955495]
 [ 1.50046453  0.61830376  1.45242571 ... -1.16235959 -0.99924657
  -1.32420121]
 [ 0.67464379 -0.47062003  0.68363569 ...  0.17528971 -0.70860397
   0.07955495]]


In [16]:
import pickle

with open('X_saved.dat', 'wb') as f:
    pickle.dump(temp_X, f) 
    
with open('Y_saved.dat', 'wb') as f:
    pickle.dump(Y, f) 


In [17]:
with open('X_saved.dat', 'rb') as f:
    X_load = pickle.load(f)
    
with open('Y_saved.dat', 'rb') as f:
    Y_load = pickle.load(f)

In [18]:
print(len(X_load))
print(X_load)
print(len(Y_load))
print(Y_load)

4803
[[ 1.39723694 -0.03505051  1.23277142 ...  1.51293901 -1.58053177
   1.20255988]
 [ 0.98432657 -0.68840479  0.90328998 ...  1.51293901 -1.58053177
   1.20255988]
 [-0.15117695 -2.43068286 -0.08515434 ...  0.97787929  0.16332384
   1.20255988]
 ...
 [ 0.26173342  0.400519    0.46398139 ...  0.17528971 -0.12731877
   0.07955495]
 [ 1.50046453  0.61830376  1.45242571 ... -1.16235959 -0.99924657
  -1.32420121]
 [ 0.67464379 -0.47062003  0.68363569 ...  0.17528971 -0.70860397
   0.07955495]]
4803
[[ 0.  1.]
 [ 0.  1.]
 [ 0.  1.]
 ...
 [ 0.  1.]
 [ 1. -0.]
 [ 0.  1.]]


In [19]:
from sklearn.model_selection import train_test_split

tr_X, te_X, tr_Y, te_Y = train_test_split(X_load, Y_load, test_size=0.3)

In [20]:
print(len(tr_X))
print(len(te_X))
print(len(tr_Y))
print(len(te_Y))

3362
1441
3362
1441


In [1]:
print(Y)

NameError: name 'Y' is not defined